"""
API generator — produces API.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict


class ApiGenerator:
    """Generates API documentation from scan results."""

    def __init__(self, scan_data: Dict[str, Any]):
        self.data = scan_data

    def generate(self) -> str:
        """Generate API.md."""
        api = self.data.get("api", {})

        lines = [
            "# API Documentation",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Summary",
            "",
            f"| Metric | Count |",
            f"|---|---|",
            f"| **Total REST Endpoints** | {api.get('total_endpoints', 0)} |",
            f"| **GraphQL Types** | {api.get('total_graphql_types', 0)} |",
            f"| **OpenAPI Specs** | {len(api.get('openapi_specs', []))} |",
            f"| **API Versions** | {', '.join(api.get('api_versions', [])) or 'None'} |",
            "",
        ]

        # REST Endpoints grouped by path prefix
        endpoints = api.get("endpoints", [])
        if endpoints:
            # Group by first path segment
            groups: Dict[str, list] = {}
            for ep in endpoints:
                path = ep.get("path", "/")
                parts = [p for p in path.split("/") if p]
                group = parts[0] if parts else "root"
                if group not in groups:
                    groups[group] = []
                groups[group].append(ep)

            lines.extend(["## REST Endpoints", ""])
            for group_name, group_eps in sorted(groups.items()):
                lines.extend([
                    f"### /{group_name}",
                    "",
                    "| Method | Path | Function | Source |",
                    "|---|---|---|---|",
                ])
                for ep in group_eps:
                    lines.append(
                        f"| `{ep.get('method', '?')}` | `{ep.get('path', '?')}` | "
                        f"`{ep.get('function', '?')}` | `{ep.get('file', '?')}` |"
                    )
                lines.append("")

        # Auth endpoints
        auth_eps = api.get("auth_endpoints", [])
        if auth_eps:
            lines.extend([
                "## Authentication Endpoints",
                "",
                "| Method | Path | Function | File |",
                "|---|---|---|---|",
            ])
            for ep in auth_eps:
                lines.append(
                    f"| `{ep.get('method', '?')}` | `{ep.get('path', '?')}` | "
                    f"`{ep.get('function', '?')}` | `{ep.get('file', '?')}` |"
                )
            lines.append("")

        # GraphQL
        gql_types = api.get("graphql_types", [])
        if gql_types:
            lines.extend(["## GraphQL Schema", ""])
            for gql in gql_types:
                lines.append(f"### `{gql['name']}`")
                lines.append(f"*Source: `{gql.get('file', '?')}`*")
                fields = gql.get("fields", [])
                if fields:
                    lines.extend(["", "| Field | Type |", "|---|---|"])
                    for f in fields:
                        lines.append(f"| `{f['name']}` | `{f.get('type', '?')}` |")
                lines.append("")

        # Middleware
        middleware = api.get("middleware", [])
        if middleware:
            lines.extend(["## Middleware", ""])
            for mw in middleware:
                lines.append(f"- `{mw.get('path', '?')}` — `{mw.get('file', '?')}`")
            lines.append("")

        # WebSocket
        ws = api.get("websocket_endpoints", [])
        if ws:
            lines.extend(["## WebSocket Endpoints", ""])
            for w in ws:
                lines.append(f"- `{w.get('path', '?')}` — `{w.get('file', '?')}`")
            lines.append("")

        # OpenAPI specs
        specs = api.get("openapi_specs", [])
        if specs:
            lines.extend(["## OpenAPI Specifications", ""])
            for s in specs:
                lines.append(f"- `{s}`")
            lines.append("")

        if not endpoints and not gql_types:
            lines.extend([
                "## No API Endpoints Detected",
                "",
                "No REST or GraphQL endpoints were found in this project.",
                "",
            ])

        lines.extend(["---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)
