"""
Architecture generator — produces ARCHITECTURE.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List


class ArchitectureGenerator:
    """Generates architecture documentation from scan results."""

    def __init__(self, scan_data: Dict[str, Any]):
        self.data = scan_data

    def generate(self) -> str:
        """Generate ARCHITECTURE.md."""
        generic = self.data.get("generic", {})
        py = self.data.get("python", {})
        js = self.data.get("javascript", {})
        infra = self.data.get("infrastructure", {})
        api = self.data.get("api", {})
        db = self.data.get("database", {})

        lines = [
            "# System Architecture",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]

        # Architecture type detection
        arch_type = self._detect_architecture_type()
        lines.extend([
            "## Architecture Overview",
            "",
            f"**Detected Pattern**: {arch_type}",
            "",
        ])

        # Technology stack
        frameworks = set()
        for key in ["python", "javascript"]:
            if key in self.data:
                frameworks.update(self.data[key].get("frameworks", []))

        lines.extend([
            "## Technology Stack",
            "",
            "| Layer | Technologies |",
            "|---|---|",
            f"| **Language** | {generic.get('primary_language', 'Unknown')} |",
            f"| **Frameworks** | {', '.join(sorted(frameworks)) or 'None detected'} |",
            f"| **Database** | {', '.join(db.get('db_technologies', [])) or 'None detected'} |",
            f"| **Infrastructure** | {', '.join(infra.get('cloud_services', [])) or 'None detected'} |",
            f"| **CI/CD** | {', '.join(c.get('provider', '') for c in infra.get('cicd_pipelines', [])) or 'None detected'} |",
            "",
        ])

        # Project structure (top-level directories)
        dirs = generic.get("directory_tree", [])
        top_level = [d for d in dirs if d != "/" and d.count("/") == 0]
        if top_level:
            lines.extend([
                "## Project Structure",
                "",
                "```",
            ])
            for d in sorted(top_level)[:25]:
                lines.append(f"├── {d}/")
            lines.extend(["```", ""])

        # Entry points
        entry_points = []
        for key in ["python", "javascript"]:
            if key in self.data:
                entry_points.extend(self.data[key].get("entry_points", []))
        if entry_points:
            lines.extend(["## Entry Points", ""])
            for ep in entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")

        # API layer
        endpoints = api.get("endpoints", [])
        if endpoints:
            lines.extend([
                "## API Layer",
                "",
                f"**Total Endpoints**: {api.get('total_endpoints', 0)}",
                "",
                "| Method | Path | Source |",
                "|---|---|---|",
            ])
            for ep in endpoints[:30]:
                lines.append(f"| `{ep.get('method', '?')}` | `{ep.get('path', '?')}` | `{ep.get('file', '?')}` |")
            if len(endpoints) > 30:
                lines.append(f"\n*... and {len(endpoints) - 30} more endpoints. See API.md for full list.*")
            lines.append("")

        # Data layer
        if db.get("models") or db.get("tables"):
            lines.extend([
                "## Data Layer",
                "",
                f"**Tables**: {db.get('total_tables', 0)}",
                f"**ORM Models**: {db.get('total_models', 0)}",
                f"**Migrations**: {db.get('total_migrations', 0)}",
                f"**Relationships**: {db.get('total_relationships', 0)}",
                "",
            ])

        # Key design patterns
        patterns = self._detect_patterns()
        if patterns:
            lines.extend(["## Detected Design Patterns", ""])
            for p in patterns:
                lines.append(f"- {p}")
            lines.append("")

        # Infrastructure
        docker = infra.get("docker", {})
        if docker:
            lines.extend([
                "## Infrastructure",
                "",
            ])
            if docker.get("dockerfile"):
                lines.append(f"- **Dockerfile**: `{docker['dockerfile']}` (base: `{docker.get('base_image', '?')}`)")
                if docker.get("stages", 0) > 1:
                    lines.append(f"  - Multi-stage build ({docker['stages']} stages)")
                if docker.get("exposed_ports"):
                    lines.append(f"  - Exposed ports: {', '.join(docker['exposed_ports'])}")
            if docker.get("compose_file"):
                lines.append(f"- **Docker Compose**: `{docker['compose_file']}`")
                services = docker.get("services", [])
                if services:
                    lines.append(f"  - Services: {', '.join(services)}")
            lines.append("")

        lines.extend(["---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)

    def _detect_architecture_type(self) -> str:
        """Heuristically detect the architecture pattern."""
        generic = self.data.get("generic", {})
        dirs = set(generic.get("directory_tree", []))
        infra = self.data.get("infrastructure", {})
        api = self.data.get("api", {})
        js = self.data.get("javascript", {})

        patterns = []

        # Monolith vs microservices
        compose_services = infra.get("docker", {}).get("services", [])
        if len(compose_services) > 3:
            patterns.append("Microservices")
        elif compose_services:
            patterns.append("Containerized Monolith")

        # MVC
        mvc_dirs = {"models", "views", "controllers", "templates"}
        if len(mvc_dirs & dirs) >= 2:
            patterns.append("MVC")

        # Frontend SPA
        if js.get("frameworks"):
            for fw in js["frameworks"]:
                if fw in {"react", "vue", "angular", "svelte"}:
                    patterns.append("Single Page Application (SPA)")
                    break
                if fw in {"next", "nuxt"}:
                    patterns.append("Server-Side Rendered (SSR)")
                    break

        # REST API
        if api.get("total_endpoints", 0) > 0:
            patterns.append("REST API")

        # GraphQL
        if api.get("total_graphql_types", 0) > 0:
            patterns.append("GraphQL API")

        # Serverless
        if "serverless" in " ".join(infra.get("cloud_services", [])).lower():
            patterns.append("Serverless")

        return " + ".join(patterns) if patterns else "Monolith"

    def _detect_patterns(self) -> List[str]:
        """Detect common design patterns."""
        patterns = []
        py = self.data.get("python", {})
        js = self.data.get("javascript", {})
        generic = self.data.get("generic", {})
        dirs = set(generic.get("directory_tree", []))

        # Repository pattern
        repo_keywords = {"repository", "repositories", "repo"}
        if repo_keywords & dirs:
            patterns.append("Repository Pattern")

        # Service layer
        if {"services", "service"} & dirs:
            patterns.append("Service Layer")

        # Middleware
        if {"middleware", "middlewares"} & dirs:
            patterns.append("Middleware Pipeline")

        # Event-driven
        for key in ["python", "javascript"]:
            if key in self.data:
                imports = dict(self.data[key].get("top_imports", []))
                if any(k in imports for k in ["celery", "rabbitmq", "kafka", "redis", "bull", "bee-queue"]):
                    patterns.append("Event-Driven / Message Queue")
                    break

        # Factory pattern
        if {"factories", "factory"} & dirs:
            patterns.append("Factory Pattern")

        # DTO / Schema pattern
        if {"schemas", "dtos", "dto", "serializers"} & dirs:
            patterns.append("DTO/Schema Pattern")

        return patterns
