"""
Database generator — produces DATABASE.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict


class DatabaseGenerator:
    """Generates database documentation from scan results."""

    def __init__(self, scan_data: Dict[str, Any]):
        self.data = scan_data

    def generate(self) -> str:
        """Generate DATABASE.md."""
        db = self.data.get("database", {})

        lines = [
            "# Database Schema",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Summary",
            "",
            f"| Metric | Count |",
            f"|---|---|",
            f"| **SQL Tables** | {db.get('total_tables', 0)} |",
            f"| **ORM Models** | {db.get('total_models', 0)} |",
            f"| **Migrations** | {db.get('total_migrations', 0)} |",
            f"| **Relationships** | {db.get('total_relationships', 0)} |",
            f"| **Technologies** | {', '.join(db.get('db_technologies', [])) or 'None detected'} |",
            "",
        ]

        # SQL Tables
        tables = db.get("tables", [])
        if tables:
            lines.extend(["## SQL Tables", ""])
            for table in tables:
                lines.extend([
                    f"### `{table['name']}`",
                    f"*Source: `{table.get('file', 'unknown')}`*",
                    "",
                    "| Column | Type | Nullable | PK |",
                    "|---|---|---|---|",
                ])
                for col in table.get("columns", []):
                    pk = "✅" if col.get("primary_key") else ""
                    nullable = "Yes" if col.get("nullable") else "No"
                    lines.append(f"| `{col['name']}` | `{col['type']}` | {nullable} | {pk} |")
                lines.append("")

        # ORM Models
        models = db.get("models", [])
        if models:
            lines.extend(["## ORM Models", ""])
            for model in models:
                orm = model.get("orm", "unknown")
                lines.extend([
                    f"### `{model['name']}` ({orm})",
                    f"*Source: `{model.get('file', 'unknown')}`*",
                    "",
                ])
                fields = model.get("fields", [])
                if fields:
                    lines.extend(["| Field | Type |", "|---|---|"])
                    for field in fields:
                        lines.append(f"| `{field['name']}` | `{field.get('type', '?')}` |")
                    lines.append("")

        # Relationships
        rels = db.get("relationships", [])
        if rels:
            lines.extend([
                "## Relationships",
                "",
                "| From Table | Column | To Table |",
                "|---|---|---|",
            ])
            for rel in rels:
                lines.append(f"| `{rel['from_table']}` | `{rel['from_column']}` | `{rel['to_table']}` |")
            lines.append("")

        # Indexes
        indexes = db.get("indexes", [])
        if indexes:
            lines.extend([
                "## Indexes",
                "",
                "| Name | Table | Columns |",
                "|---|---|---|",
            ])
            for idx in indexes:
                lines.append(f"| `{idx['name']}` | `{idx['table']}` | `{idx['columns']}` |")
            lines.append("")

        # Migrations
        migrations = db.get("migrations", [])
        if migrations:
            lines.extend(["## Migrations", ""])
            for m in migrations[:30]:
                lines.append(f"- `{m['file']}` ({m.get('type', '?')})")
            if len(migrations) > 30:
                lines.append(f"\n*... and {len(migrations) - 30} more migrations.*")
            lines.append("")

        if not tables and not models:
            lines.extend([
                "## No Database Schema Detected",
                "",
                "No SQL tables, ORM models, or database migrations were found.",
                "If this project uses a database, ensure schema files are in the project directory.",
                "",
            ])

        lines.extend(["---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)
