"""
Health generator — produces a project health dashboard.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List


class HealthGenerator:
    """Generates project health dashboard from scan results."""

    def __init__(self, scan_data: Dict[str, Any], aios_dir: str = ""):
        self.data = scan_data
        self.aios_dir = aios_dir

    def generate(self) -> str:
        """Generate project health report."""
        generic = self.data.get("generic", {})
        security = self.data.get("security", {})
        git = self.data.get("git", {})
        db = self.data.get("database", {})
        api = self.data.get("api", {})
        infra = self.data.get("infrastructure", {})

        # Calculate scores
        security_score = security.get("security_score", 0)
        test_score = self._calculate_test_score()
        doc_score = self._calculate_doc_score()
        infra_score = self._calculate_infra_score()
        code_quality_score = self._calculate_code_quality_score()

        # Overall health
        weights = {
            "security": 0.30,
            "testing": 0.20,
            "documentation": 0.15,
            "infrastructure": 0.15,
            "code_quality": 0.20,
        }
        overall = int(
            security_score * weights["security"]
            + test_score * weights["testing"]
            + doc_score * weights["documentation"]
            + infra_score * weights["infrastructure"]
            + code_quality_score * weights["code_quality"]
        )

        # Risk areas
        risks = self._identify_risks()

        lines = [
            "# Project Health Dashboard",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Overall Health Score",
            "",
            f"```",
            f"  Overall: {overall}/100  [{self._bar(overall)}]",
            f"```",
            "",
            "## Score Breakdown",
            "",
            "| Category | Score | Weight | Status |",
            "|---|---|---|---|",
            f"| 🔒 Security | {security_score}/100 | 30% | {self._status(security_score)} |",
            f"| 🧪 Testing | {test_score}/100 | 20% | {self._status(test_score)} |",
            f"| 📝 Documentation | {doc_score}/100 | 15% | {self._status(doc_score)} |",
            f"| 🏗️ Infrastructure | {infra_score}/100 | 15% | {self._status(infra_score)} |",
            f"| 💎 Code Quality | {code_quality_score}/100 | 20% | {self._status(code_quality_score)} |",
            "",
            "## Project Metrics",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| **Total Source Files** | {generic.get('total_source_files', 0):,} |",
            f"| **Total Lines of Code** | {generic.get('total_loc', 0):,} |",
            f"| **Total Commits** | {git.get('total_commits', 0):,} |",
            f"| **Contributors** | {len(git.get('contributors', []))} |",
            f"| **API Endpoints** | {api.get('total_endpoints', 0)} |",
            f"| **Database Models** | {db.get('total_models', 0)} |",
            f"| **Security Score** | {security_score}/100 |",
            f"| **Secrets Exposed** | {security.get('total_secrets_found', 0)} |",
            "",
        ]

        # Deployment status
        lines.extend([
            "## Deployment Status",
            "",
            f"- **Docker**: {'✅ Configured' if infra.get('has_docker') else '❌ Not configured'}",
            f"- **CI/CD**: {'✅ Configured' if infra.get('has_cicd') else '❌ Not configured'}",
            f"- **Kubernetes**: {'✅ Configured' if infra.get('has_kubernetes') else '❌ Not configured'}",
            "",
        ])

        # Risk areas
        if risks:
            lines.extend([
                "## ⚠️ Risk Areas",
                "",
            ])
            for risk in risks:
                lines.append(f"- **{risk['level']}**: {risk['description']}")
            lines.append("")

        # Recommendations
        recommendations = self._generate_recommendations()
        if recommendations:
            lines.extend([
                "## Recommendations",
                "",
            ])
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        lines.extend(["---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)

    def _bar(self, score: int) -> str:
        filled = int(score / 5)
        return "█" * filled + "░" * (20 - filled)

    def _status(self, score: int) -> str:
        if score >= 80:
            return "🟢 Excellent"
        elif score >= 60:
            return "🟡 Good"
        elif score >= 40:
            return "🟠 Fair"
        else:
            return "🔴 Poor"

    def _calculate_test_score(self) -> int:
        score = 0
        for key in ["python", "javascript"]:
            if key in self.data:
                total = self.data[key].get("total_files", 0)
                test = self.data[key].get("total_test_files", 0)
                if total > 0:
                    ratio = test / total
                    score = max(score, min(100, int(ratio * 500)))  # 20% test files = 100
        generic = self.data.get("generic", {})
        if generic.get("has_tests"):
            score = max(score, 30)
        return score

    def _calculate_doc_score(self) -> int:
        score = 0
        generic = self.data.get("generic", {})
        if generic.get("has_readme"):
            score += 40
        if generic.get("has_docs"):
            score += 30
        if generic.get("has_license"):
            score += 15
        # Check for inline documentation
        api = self.data.get("api", {})
        if api.get("openapi_specs"):
            score += 15
        return min(100, score)

    def _calculate_infra_score(self) -> int:
        score = 0
        infra = self.data.get("infrastructure", {})
        if infra.get("has_docker"):
            score += 30
        if infra.get("has_cicd"):
            score += 30
        if infra.get("has_kubernetes"):
            score += 15
        if infra.get("cloud_services"):
            score += 10
        env_vars = infra.get("environment_variables", [])
        if env_vars:
            score += 15
        return min(100, score)

    def _calculate_code_quality_score(self) -> int:
        score = 50  # Start at baseline
        generic = self.data.get("generic", {})

        # Deduct for very large files
        largest = generic.get("largest_files", [])
        if largest:
            biggest_loc = largest[0].get("loc", 0)
            if biggest_loc > 1000:
                score -= 10
            if biggest_loc > 2000:
                score -= 10

        # Bonus for modular structure
        dirs = generic.get("total_directories", 0)
        files = generic.get("total_source_files", 1)
        if dirs > 5:
            score += 15
        if files / max(dirs, 1) < 15:
            score += 10

        # Bonus for tests
        if generic.get("has_tests"):
            score += 15

        return max(0, min(100, score))

    def _identify_risks(self) -> List[Dict[str, str]]:
        risks = []
        security = self.data.get("security", {})

        if security.get("total_secrets_found", 0) > 0:
            risks.append({"level": "CRITICAL", "description": f"{security['total_secrets_found']} hardcoded secrets found in source code"})
        if security.get("total_sql_injection_risks", 0) > 0:
            risks.append({"level": "HIGH", "description": f"{security['total_sql_injection_risks']} potential SQL injection vulnerabilities"})
        if security.get("total_xss_risks", 0) > 0:
            risks.append({"level": "MEDIUM", "description": f"{security['total_xss_risks']} potential XSS vulnerabilities"})
        if not security.get("security_features", {}).get("authentication"):
            risks.append({"level": "HIGH", "description": "No authentication system detected"})
        if not security.get("security_features", {}).get("rate_limiting"):
            risks.append({"level": "MEDIUM", "description": "No rate limiting configured"})

        infra = self.data.get("infrastructure", {})
        if not infra.get("has_cicd"):
            risks.append({"level": "MEDIUM", "description": "No CI/CD pipeline configured"})

        return risks

    def _generate_recommendations(self) -> List[str]:
        recs = []
        security = self.data.get("security", {})
        infra = self.data.get("infrastructure", {})
        generic = self.data.get("generic", {})

        if security.get("total_secrets_found", 0) > 0:
            recs.append("🔴 **Immediately** remove hardcoded secrets and use environment variables")
        if not security.get("security_features", {}).get("authentication"):
            recs.append("🔒 Implement authentication (JWT, OAuth, or session-based)")
        if not security.get("security_features", {}).get("rate_limiting"):
            recs.append("🛡️ Add rate limiting to API endpoints")
        if not infra.get("has_cicd"):
            recs.append("🏗️ Set up CI/CD pipeline for automated testing and deployment")
        if not generic.get("has_readme"):
            recs.append("📝 Create a README.md with project setup instructions")
        if not generic.get("has_tests"):
            recs.append("🧪 Add automated tests to improve code reliability")
        if not infra.get("has_docker"):
            recs.append("🐳 Containerize the application with Docker for consistency")

        return recs
