"""
Project generator — produces PROJECT.md, CURRENT_STATE.md, FEATURES.md, MODULES.md, DEPENDENCIES.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict


class ProjectGenerator:
    """Generates project-level markdown documents from scan results."""

    def __init__(self, scan_data: Dict[str, Any], project_name: str = ""):
        self.data = scan_data
        self.project_name = project_name or "Unnamed Project"

    def generate_project_md(self) -> str:
        """Generate PROJECT.md — main project overview."""
        generic = self.data.get("generic", {})
        git = self.data.get("git", {})
        infra = self.data.get("infrastructure", {})

        pkg_name = ""
        for pm in infra.get("package_managers", []):
            if pm.get("name"):
                pkg_name = pm["name"]
                break

        name = pkg_name or self.project_name
        primary_lang = generic.get("primary_language", "Unknown")
        total_files = generic.get("total_source_files", 0)
        total_loc = generic.get("total_loc", 0)
        remote = git.get("remote_url", "")

        frameworks = set()
        for key in ["python", "javascript"]:
            if key in self.data:
                frameworks.update(self.data[key].get("frameworks", []))

        lines = [
            f"# {name}",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Project Overview",
            "",
            f"| Attribute | Value |",
            f"|---|---|",
            f"| **Project Name** | {name} |",
            f"| **Primary Language** | {primary_lang} |",
            f"| **Total Source Files** | {total_files:,} |",
            f"| **Total Lines of Code** | {total_loc:,} |",
            f"| **Frameworks** | {', '.join(sorted(frameworks)) or 'None detected'} |",
            f"| **Repository** | {remote or 'Not configured'} |",
            f"| **Git Initialized** | {'Yes' if git.get('git_initialized') else 'No'} |",
        ]

        if git.get("total_commits"):
            lines.append(f"| **Total Commits** | {git['total_commits']:,} |")
            lines.append(f"| **Contributors** | {len(git.get('contributors', []))} |")
            lines.append(f"| **First Commit** | {git.get('first_commit_date', 'N/A')} |")
            lines.append(f"| **Last Commit** | {git.get('last_commit_date', 'N/A')} |")

        # Languages
        languages = generic.get("languages", {})
        if languages:
            lines.extend([
                "",
                "## Language Breakdown",
                "",
                "| Language | Files | Lines of Code |",
                "|---|---|---|",
            ])
            for lang, stats in list(languages.items())[:15]:
                lines.append(f"| {lang} | {stats['files']:,} | {stats['loc']:,} |")

        # Cloud & infrastructure
        cloud = infra.get("cloud_services", [])
        if cloud:
            lines.extend(["", "## Cloud & Infrastructure", ""])
            for svc in cloud:
                lines.append(f"- {svc}")

        if infra.get("has_docker"):
            lines.append(f"- Docker (base: {infra.get('docker', {}).get('base_image', 'N/A')})")
        if infra.get("has_cicd"):
            for ci in infra.get("cicd_pipelines", []):
                lines.append(f"- CI/CD: {ci.get('provider', 'unknown')} ({ci.get('file', '')})")

        lines.extend(["", "---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)

    def generate_current_state_md(self) -> str:
        """Generate CURRENT_STATE.md — snapshot of current development status."""
        git = self.data.get("git", {})
        generic = self.data.get("generic", {})

        lines = [
            "# Current State",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Development Status",
            "",
            f"- **Current Branch**: {git.get('current_branch', 'N/A')}",
            f"- **Total Commits**: {git.get('total_commits', 0):,}",
            f"- **Last Commit**: {git.get('last_commit_date', 'N/A')}",
            "",
        ]

        # Uncommitted changes
        changes = git.get("uncommitted_changes", {})
        if any(changes.get(k) for k in ["staged", "unstaged", "untracked"]):
            lines.extend(["## Uncommitted Changes", ""])
            if changes.get("staged"):
                lines.append(f"### Staged ({len(changes['staged'])} files)")
                for f in changes["staged"][:10]:
                    lines.append(f"- `{f}`")
            if changes.get("unstaged"):
                lines.append(f"\n### Unstaged ({len(changes['unstaged'])} files)")
                for f in changes["unstaged"][:10]:
                    lines.append(f"- `{f}`")
            if changes.get("untracked"):
                lines.append(f"\n### Untracked ({len(changes['untracked'])} files)")
                for f in changes["untracked"][:10]:
                    lines.append(f"- `{f}`")
        else:
            lines.append("## Working Directory: Clean ✅")

        # Recent commits
        recent = git.get("recent_commits", [])[:10]
        if recent:
            lines.extend(["", "## Recent Commits", "", "| Hash | Author | Date | Message |", "|---|---|---|---|"])
            for c in recent:
                msg = c["message"][:60]
                lines.append(f"| `{c['hash']}` | {c['author']} | {c['date'][:10]} | {msg} |")

        # Tags / versions
        tags = git.get("tags", [])
        if tags:
            lines.extend(["", "## Recent Tags/Versions", ""])
            for tag in tags[:10]:
                lines.append(f"- `{tag}`")

        lines.extend(["", "---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)

    def generate_features_md(self) -> str:
        """Generate FEATURES.md — feature tracking template."""
        lines = [
            "# Features",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Feature Registry",
            "",
            "| ID | Feature | Status | Module | Priority | Notes |",
            "|---|---|---|---|---|---|",
            "| F-001 | *Add features here* | 🔲 Planned | — | — | — |",
            "",
            "### Status Legend",
            "- 🔲 Planned",
            "- 🔨 In Progress",
            "- ✅ Complete",
            "- ⏸️ On Hold",
            "- ❌ Cancelled",
            "",
            "---",
            "*Update this file as features are planned and implemented.*",
            "",
        ]
        return "\n".join(lines)

    def generate_modules_md(self) -> str:
        """Generate MODULES.md — module documentation."""
        generic = self.data.get("generic", {})
        py = self.data.get("python", {})
        js = self.data.get("javascript", {})

        lines = [
            "# Modules",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Module Registry",
            "",
        ]

        # Directory-based modules
        dirs = generic.get("directory_tree", [])
        top_level = [d for d in dirs if d.count("/") <= 1 and d != "/"]
        if top_level:
            lines.extend(["| Module | Type | Description |", "|---|---|---|"])
            for d in top_level[:30]:
                lines.append(f"| `{d}` | Directory | *Add description* |")
            lines.append("")

        # Python classes as modules
        if py.get("classes"):
            lines.extend(["## Key Classes", "", "| Class | File | Methods | Bases |", "|---|---|---|---|"])
            for cls in py["classes"][:30]:
                bases = ", ".join(cls.get("bases", []))[:40]
                lines.append(f"| `{cls['name']}` | `{cls['file']}` | {cls['method_count']} | {bases} |")
            lines.append("")

        # JS components
        if js.get("components"):
            lines.extend(["## React Components", "", "| Component | File |", "|---|---|"])
            for comp in js["components"][:30]:
                lines.append(f"| `{comp['name']}` | `{comp['file']}` |")
            lines.append("")

        lines.extend(["---", "*Update this file as modules evolve.*", ""])
        return "\n".join(lines)

    def generate_dependencies_md(self) -> str:
        """Generate DEPENDENCIES.md — dependency tracking."""
        infra = self.data.get("infrastructure", {})
        py = self.data.get("python", {})
        js = self.data.get("javascript", {})

        lines = [
            "# Dependencies",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]

        # Package managers
        for pm in infra.get("package_managers", []):
            if pm.get("type") == "node":
                lines.extend([
                    f"## Node.js — {pm.get('name', 'unnamed')} (v{pm.get('version', '?')})",
                    "",
                    f"**Total dependencies**: {pm.get('total_deps', 0)}",
                    "",
                ])
                if pm.get("dependencies"):
                    lines.extend(["### Production Dependencies", ""])
                    for dep in pm["dependencies"][:40]:
                        lines.append(f"- `{dep}`")
                    lines.append("")
                if pm.get("dev_dependencies"):
                    lines.extend(["### Dev Dependencies", ""])
                    for dep in pm["dev_dependencies"][:40]:
                        lines.append(f"- `{dep}`")
                    lines.append("")
            else:
                lines.append(f"## {pm.get('type', 'unknown').title()} — `{pm.get('file', '')}`")
                lines.append("")

        # Python top imports
        if py.get("top_imports"):
            lines.extend(["## Python — Top Imports", "", "| Package | Import Count |", "|---|---|"])
            for pkg, count in py["top_imports"][:20]:
                lines.append(f"| `{pkg}` | {count} |")
            lines.append("")

        # JS top imports
        if js.get("top_imports"):
            lines.extend(["## JavaScript — Top Imports", "", "| Package | Import Count |", "|---|---|"])
            for pkg, count in js["top_imports"][:20]:
                lines.append(f"| `{pkg}` | {count} |")
            lines.append("")

        lines.extend(["---", "*Update this file when dependencies change.*", ""])
        return "\n".join(lines)
