"""
Security generator — produces SECURITY.md and ROLES_PERMISSIONS.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict


class SecurityGenerator:
    """Generates security documentation from scan results."""

    def __init__(self, scan_data: Dict[str, Any]):
        self.data = scan_data

    def generate_security_md(self) -> str:
        """Generate SECURITY.md."""
        sec = self.data.get("security", {})

        score = sec.get("security_score", 0)
        severity = sec.get("severity", "UNKNOWN")
        features = sec.get("security_features", {})

        # Score bar
        filled = int(score / 5)
        bar = "█" * filled + "░" * (20 - filled)

        lines = [
            "# Security Report",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Security Score",
            "",
            f"```",
            f"Score: {score}/100  [{bar}]  Severity: {severity}",
            f"```",
            "",
            "## Security Features",
            "",
            "| Feature | Status |",
            "|---|---|",
        ]
        feature_labels = {
            "authentication": "Authentication",
            "authorization_rbac": "Authorization (RBAC)",
            "encryption": "Encryption",
            "audit_logging": "Audit Logging",
            "rate_limiting": "Rate Limiting",
            "input_validation": "Input Validation",
            "csrf_protection": "CSRF Protection",
            "security_headers": "Security Headers",
            "https_enforcement": "HTTPS Enforcement",
        }
        for key, label in feature_labels.items():
            status = "✅ Detected" if features.get(key) else "❌ Missing"
            lines.append(f"| {label} | {status} |")
        lines.append("")

        # Secrets found
        secrets = sec.get("secrets_found", [])
        if secrets:
            lines.extend([
                "## ⚠️ Secrets Detected in Source",
                "",
                f"**{len(secrets)} potential secret(s) found!**",
                "",
                "| Type | File | Preview |",
                "|---|---|---|",
            ])
            for s in secrets[:20]:
                preview = s.get("line_preview", "")[:50]
                lines.append(f"| {s['type']} | `{s['file']}` | `{preview}...` |")
            lines.append("")

        # SQL injection risks
        sqli = sec.get("sql_injection_risks", [])
        if sqli:
            lines.extend([
                "## ⚠️ SQL Injection Risks",
                "",
                "The following files contain potential SQL injection vulnerabilities:",
                "",
            ])
            for risk in sqli:
                lines.append(f"- `{risk['file']}`")
            lines.append("")

        # XSS risks
        xss = sec.get("xss_risks", [])
        if xss:
            lines.extend([
                "## ⚠️ XSS Risks",
                "",
                "The following files use dangerous HTML injection patterns:",
                "",
            ])
            for risk in xss:
                lines.append(f"- `{risk['file']}`")
            lines.append("")

        # CORS issues
        cors = sec.get("cors_issues", [])
        if cors:
            lines.extend(["## ⚠️ CORS Configuration Issues", ""])
            for issue in cors:
                lines.append(f"- `{issue['file']}`: {issue.get('issue', '')}")
            lines.append("")

        # Missing security features
        missing = sec.get("missing_security_features", [])
        if missing:
            lines.extend([
                "## Recommendations",
                "",
                "The following security features are recommended but not detected:",
                "",
            ])
            for m in missing:
                lines.append(f"- ❌ {m}")
            lines.append("")

        # Auth patterns
        auth = sec.get("auth_patterns", [])
        if auth:
            lines.extend(["## Authentication Patterns Found", ""])
            for a in auth:
                lines.append(f"- **{a['type']}** — `{a['file']}`")
            lines.append("")

        lines.extend(["---", f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""])
        return "\n".join(lines)

    def generate_roles_permissions_md(self) -> str:
        """Generate ROLES_PERMISSIONS.md."""
        sec = self.data.get("security", {})

        lines = [
            "# Roles & Permissions",
            "",
            f"> Auto-generated by AIOS on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]

        rbac = sec.get("rbac_patterns", [])
        if rbac:
            lines.extend([
                "## RBAC Patterns Detected",
                "",
                "| Pattern | File |",
                "|---|---|",
            ])
            seen = set()
            for r in rbac:
                key = f"{r.get('pattern', '')}|{r.get('file', '')}"
                if key not in seen:
                    lines.append(f"| `{r.get('pattern', '?')}` | `{r.get('file', '?')}` |")
                    seen.add(key)
            lines.append("")
        else:
            lines.extend([
                "## No RBAC System Detected",
                "",
                "No role-based access control patterns were found.",
                "Consider implementing RBAC for production applications.",
                "",
            ])

        lines.extend([
            "## Role Definitions",
            "",
            "*Define your application roles below:*",
            "",
            "| Role | Permissions | Description |",
            "|---|---|---|",
            "| `admin` | *Full access* | *System administrator* |",
            "| `user` | *Standard access* | *Regular user* |",
            "| *Add roles here* | — | — |",
            "",
            "## Permission Matrix",
            "",
            "*Define the permission matrix for your application:*",
            "",
            "| Resource | Admin | User | Guest |",
            "|---|---|---|---|",
            "| *Resource 1* | ✅ CRUD | ✅ Read | ❌ None |",
            "| *Add resources* | — | — | — |",
            "",
            "---",
            f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
            "",
        ])
        return "\n".join(lines)
